class CurrencyMetadata {
  final String symbol;
  final String fallbackName;

  const CurrencyMetadata({
    required this.symbol,
    required this.fallbackName,
  });
}

const Map<String, CurrencyMetadata> currencyMetadataByCode = {
  'AED': CurrencyMetadata(symbol: r'د.إ', fallbackName: 'UAE Dirham'),
  'AFN': CurrencyMetadata(symbol: r'؋', fallbackName: 'Afghan Afghani'),
  'ALL': CurrencyMetadata(symbol: r'L', fallbackName: 'Albanian Lek'),
  'AMD': CurrencyMetadata(symbol: r'֏', fallbackName: 'Armenian Dram'),
  'ANG': CurrencyMetadata(symbol: r'ƒ', fallbackName: 'Netherlands Antillean Guilder'),
  'AOA': CurrencyMetadata(symbol: r'Kz', fallbackName: 'Angolan Kwanza'),
  'ARS': CurrencyMetadata(symbol: r'$', fallbackName: 'Argentine Peso'),
  'AUD': CurrencyMetadata(symbol: r'A$', fallbackName: 'Australian Dollar'),
  'AWG': CurrencyMetadata(symbol: r'ƒ', fallbackName: 'Aruban Florin'),
  'AZN': CurrencyMetadata(symbol: r'₼', fallbackName: 'Azerbaijani Manat'),
  'BAM': CurrencyMetadata(symbol: r'KM', fallbackName: 'Bosnia and Herzegovina Convertible Mark'),
  'BBD': CurrencyMetadata(symbol: r'Bds$', fallbackName: 'Barbadian Dollar'),
  'BDT': CurrencyMetadata(symbol: r'৳', fallbackName: 'Bangladeshi Taka'),
  'BGN': CurrencyMetadata(symbol: r'лв', fallbackName: 'Bulgarian Lev'),
  'BHD': CurrencyMetadata(symbol: r'.د.ب', fallbackName: 'Bahraini Dinar'),
  'BIF': CurrencyMetadata(symbol: r'FBu', fallbackName: 'Burundian Franc'),
  'BMD': CurrencyMetadata(symbol: r'BD$', fallbackName: 'Bermudian Dollar'),
  'BND': CurrencyMetadata(symbol: r'B$', fallbackName: 'Brunei Dollar'),
  'BOB': CurrencyMetadata(symbol: r'Bs.', fallbackName: 'Bolivian Boliviano'),
  'BRL': CurrencyMetadata(symbol: r'R$', fallbackName: 'Brazilian Real'),
  'BSD': CurrencyMetadata(symbol: r'B$', fallbackName: 'Bahamian Dollar'),
  'BTN': CurrencyMetadata(symbol: r'Nu.', fallbackName: 'Bhutanese Ngultrum'),
  'BWP': CurrencyMetadata(symbol: r'P', fallbackName: 'Botswana Pula'),
  'BYN': CurrencyMetadata(symbol: r'Br', fallbackName: 'Belarusian Ruble'),
  'BZD': CurrencyMetadata(symbol: r'BZ$', fallbackName: 'Belize Dollar'),
  'CAD': CurrencyMetadata(symbol: r'C$', fallbackName: 'Canadian Dollar'),
  'CDF': CurrencyMetadata(symbol: r'FC', fallbackName: 'Congolese Franc'),
  'CHF': CurrencyMetadata(symbol: r'CHF', fallbackName: 'Swiss Franc'),
  'CLP': CurrencyMetadata(symbol: r'CLP$', fallbackName: 'Chilean Peso'),
  'CNY': CurrencyMetadata(symbol: r'¥', fallbackName: 'Chinese Yuan'),
  'COP': CurrencyMetadata(symbol: r'COL$', fallbackName: 'Colombian Peso'),
  'CRC': CurrencyMetadata(symbol: r'₡', fallbackName: 'Costa Rican Colon'),
  'CUP': CurrencyMetadata(symbol: r'₱', fallbackName: 'Cuban Peso'),
  'CVE': CurrencyMetadata(symbol: r'Esc', fallbackName: 'Cape Verdean Escudo'),
  'CZK': CurrencyMetadata(symbol: r'Kč', fallbackName: 'Czech Koruna'),
  'DJF': CurrencyMetadata(symbol: r'Fdj', fallbackName: 'Djiboutian Franc'),
  'DKK': CurrencyMetadata(symbol: r'kr', fallbackName: 'Danish Krone'),
  'DOP': CurrencyMetadata(symbol: r'RD$', fallbackName: 'Dominican Peso'),
  'DZD': CurrencyMetadata(symbol: r'دج', fallbackName: 'Algerian Dinar'),
  'EGP': CurrencyMetadata(symbol: r'E£', fallbackName: 'Egyptian Pound'),
  'ERN': CurrencyMetadata(symbol: r'Nfk', fallbackName: 'Eritrean Nakfa'),
  'ETB': CurrencyMetadata(symbol: r'Br', fallbackName: 'Ethiopian Birr'),
  'EUR': CurrencyMetadata(symbol: r'€', fallbackName: 'Euro'),
  'FJD': CurrencyMetadata(symbol: r'FJ$', fallbackName: 'Fijian Dollar'),
  'FKP': CurrencyMetadata(symbol: r'£', fallbackName: 'Falkland Islands Pound'),
  'GBP': CurrencyMetadata(symbol: r'£', fallbackName: 'British Pound'),
  'GEL': CurrencyMetadata(symbol: r'₾', fallbackName: 'Georgian Lari'),
  'GHS': CurrencyMetadata(symbol: r'₵', fallbackName: 'Ghanaian Cedi'),
  'GIP': CurrencyMetadata(symbol: r'£', fallbackName: 'Gibraltar Pound'),
  'GMD': CurrencyMetadata(symbol: r'D', fallbackName: 'Gambian Dalasi'),
  'GNF': CurrencyMetadata(symbol: r'FG', fallbackName: 'Guinean Franc'),
  'GTQ': CurrencyMetadata(symbol: r'Q', fallbackName: 'Guatemalan Quetzal'),
  'GYD': CurrencyMetadata(symbol: r'GY$', fallbackName: 'Guyanese Dollar'),
  'HKD': CurrencyMetadata(symbol: r'HK$', fallbackName: 'Hong Kong Dollar'),
  'HNL': CurrencyMetadata(symbol: r'L', fallbackName: 'Honduran Lempira'),
  'HRK': CurrencyMetadata(symbol: r'kn', fallbackName: 'Croatian Kuna'),
  'HTG': CurrencyMetadata(symbol: r'G', fallbackName: 'Haitian Gourde'),
  'HUF': CurrencyMetadata(symbol: r'Ft', fallbackName: 'Hungarian Forint'),
  'IDR': CurrencyMetadata(symbol: r'Rp', fallbackName: 'Indonesian Rupiah'),
  'ILS': CurrencyMetadata(symbol: r'₪', fallbackName: 'Israeli New Shekel'),
  'INR': CurrencyMetadata(symbol: r'₹', fallbackName: 'Indian Rupee'),
  'IQD': CurrencyMetadata(symbol: r'ع.د', fallbackName: 'Iraqi Dinar'),
  'IRR': CurrencyMetadata(symbol: r'﷼', fallbackName: 'Iranian Rial'),
  'ISK': CurrencyMetadata(symbol: r'kr', fallbackName: 'Icelandic Krona'),
  'JMD': CurrencyMetadata(symbol: r'J$', fallbackName: 'Jamaican Dollar'),
  'JOD': CurrencyMetadata(symbol: r'JD', fallbackName: 'Jordanian Dinar'),
  'JPY': CurrencyMetadata(symbol: r'¥', fallbackName: 'Japanese Yen'),
  'KES': CurrencyMetadata(symbol: r'KSh', fallbackName: 'Kenyan Shilling'),
  'KGS': CurrencyMetadata(symbol: r'сом', fallbackName: 'Kyrgyzstani Som'),
  'KHR': CurrencyMetadata(symbol: r'៛', fallbackName: 'Cambodian Riel'),
  'KMF': CurrencyMetadata(symbol: r'CF', fallbackName: 'Comorian Franc'),
  'KRW': CurrencyMetadata(symbol: r'₩', fallbackName: 'South Korean Won'),
  'KWD': CurrencyMetadata(symbol: r'د.ك', fallbackName: 'Kuwaiti Dinar'),
  'KYD': CurrencyMetadata(symbol: r'CI$', fallbackName: 'Cayman Islands Dollar'),
  'KZT': CurrencyMetadata(symbol: r'₸', fallbackName: 'Kazakhstani Tenge'),
  'LAK': CurrencyMetadata(symbol: r'₭', fallbackName: 'Lao Kip'),
  'LBP': CurrencyMetadata(symbol: r'L£', fallbackName: 'Lebanese Pound'),
  'LKR': CurrencyMetadata(symbol: r'Rs', fallbackName: 'Sri Lankan Rupee'),
  'LRD': CurrencyMetadata(symbol: r'L$', fallbackName: 'Liberian Dollar'),
  'LSL': CurrencyMetadata(symbol: r'L', fallbackName: 'Lesotho Loti'),
  'LYD': CurrencyMetadata(symbol: r'LD', fallbackName: 'Libyan Dinar'),
  'MAD': CurrencyMetadata(symbol: r'د.م.', fallbackName: 'Moroccan Dirham'),
  'MDL': CurrencyMetadata(symbol: r'L', fallbackName: 'Moldovan Leu'),
  'MGA': CurrencyMetadata(symbol: r'Ar', fallbackName: 'Malagasy Ariary'),
  'MKD': CurrencyMetadata(symbol: r'ден', fallbackName: 'Macedonian Denar'),
  'MMK': CurrencyMetadata(symbol: r'K', fallbackName: 'Myanmar Kyat'),
  'MNT': CurrencyMetadata(symbol: r'₮', fallbackName: 'Mongolian Tugrik'),
  'MOP': CurrencyMetadata(symbol: r'MOP$', fallbackName: 'Macanese Pataca'),
  'MRU': CurrencyMetadata(symbol: r'UM', fallbackName: 'Mauritanian Ouguiya'),
  'MUR': CurrencyMetadata(symbol: r'₨', fallbackName: 'Mauritian Rupee'),
  'MVR': CurrencyMetadata(symbol: r'Rf', fallbackName: 'Maldivian Rufiyaa'),
  'MWK': CurrencyMetadata(symbol: r'MK', fallbackName: 'Malawian Kwacha'),
  'MXN': CurrencyMetadata(symbol: r'MX$', fallbackName: 'Mexican Peso'),
  'MYR': CurrencyMetadata(symbol: r'RM', fallbackName: 'Malaysian Ringgit'),
  'MZN': CurrencyMetadata(symbol: r'MT', fallbackName: 'Mozambican Metical'),
  'NAD': CurrencyMetadata(symbol: r'N$', fallbackName: 'Namibian Dollar'),
  'NGN': CurrencyMetadata(symbol: r'₦', fallbackName: 'Nigerian Naira'),
  'NIO': CurrencyMetadata(symbol: r'C$', fallbackName: 'Nicaraguan Cordoba'),
  'NOK': CurrencyMetadata(symbol: r'kr', fallbackName: 'Norwegian Krone'),
  'NPR': CurrencyMetadata(symbol: r'₨', fallbackName: 'Nepalese Rupee'),
  'NZD': CurrencyMetadata(symbol: r'NZ$', fallbackName: 'New Zealand Dollar'),
  'OMR': CurrencyMetadata(symbol: r'ر.ع.', fallbackName: 'Omani Rial'),
  'PAB': CurrencyMetadata(symbol: r'B/.', fallbackName: 'Panamanian Balboa'),
  'PEN': CurrencyMetadata(symbol: r'S/', fallbackName: 'Peruvian Sol'),
  'PGK': CurrencyMetadata(symbol: r'K', fallbackName: 'Papua New Guinean Kina'),
  'PHP': CurrencyMetadata(symbol: r'₱', fallbackName: 'Philippine Peso'),
  'PKR': CurrencyMetadata(symbol: r'₨', fallbackName: 'Pakistani Rupee'),
  'PLN': CurrencyMetadata(symbol: r'zł', fallbackName: 'Polish Zloty'),
  'PYG': CurrencyMetadata(symbol: r'₲', fallbackName: 'Paraguayan Guarani'),
  'QAR': CurrencyMetadata(symbol: r'ر.ق', fallbackName: 'Qatari Riyal'),
  'RON': CurrencyMetadata(symbol: r'lei', fallbackName: 'Romanian Leu'),
  'RSD': CurrencyMetadata(symbol: r'дин', fallbackName: 'Serbian Dinar'),
  'RUB': CurrencyMetadata(symbol: r'₽', fallbackName: 'Russian Ruble'),
  'RWF': CurrencyMetadata(symbol: r'RF', fallbackName: 'Rwandan Franc'),
  'SAR': CurrencyMetadata(symbol: r'ر.س', fallbackName: 'Saudi Riyal'),
  'SBD': CurrencyMetadata(symbol: r'SI$', fallbackName: 'Solomon Islands Dollar'),
  'SCR': CurrencyMetadata(symbol: r'₨', fallbackName: 'Seychellois Rupee'),
  'SDG': CurrencyMetadata(symbol: r'ج.س.', fallbackName: 'Sudanese Pound'),
  'SEK': CurrencyMetadata(symbol: r'kr', fallbackName: 'Swedish Krona'),
  'SGD': CurrencyMetadata(symbol: r'S$', fallbackName: 'Singapore Dollar'),
  'SHP': CurrencyMetadata(symbol: r'£', fallbackName: 'Saint Helena Pound'),
  'SLE': CurrencyMetadata(symbol: r'Le', fallbackName: 'Sierra Leonean Leone'),
  'SOS': CurrencyMetadata(symbol: r'Sh', fallbackName: 'Somali Shilling'),
  'SRD': CurrencyMetadata(symbol: r'SRD$', fallbackName: 'Surinamese Dollar'),
  'STN': CurrencyMetadata(symbol: r'Db', fallbackName: 'Sao Tome and Principe Dobra'),
  'SVC': CurrencyMetadata(symbol: r'SV$', fallbackName: 'Salvadoran Colon'),
  'SYP': CurrencyMetadata(symbol: r'£S', fallbackName: 'Syrian Pound'),
  'SZL': CurrencyMetadata(symbol: r'E', fallbackName: 'Eswatini Lilangeni'),
  'THB': CurrencyMetadata(symbol: r'฿', fallbackName: 'Thai Baht'),
  'TJS': CurrencyMetadata(symbol: r'ЅМ', fallbackName: 'Tajikistani Somoni'),
  'TMT': CurrencyMetadata(symbol: r'm', fallbackName: 'Turkmenistani Manat'),
  'TND': CurrencyMetadata(symbol: r'د.ت', fallbackName: 'Tunisian Dinar'),
  'TOP': CurrencyMetadata(symbol: r'T$', fallbackName: 'Tongan Paanga'),
  'TRY': CurrencyMetadata(symbol: r'₺', fallbackName: 'Turkish Lira'),
  'TTD': CurrencyMetadata(symbol: r'TT$', fallbackName: 'Trinidad and Tobago Dollar'),
  'TWD': CurrencyMetadata(symbol: r'NT$', fallbackName: 'New Taiwan Dollar'),
  'TZS': CurrencyMetadata(symbol: r'Sh', fallbackName: 'Tanzanian Shilling'),
  'UAH': CurrencyMetadata(symbol: r'₴', fallbackName: 'Ukrainian Hryvnia'),
  'UGX': CurrencyMetadata(symbol: r'USh', fallbackName: 'Ugandan Shilling'),
  'USD': CurrencyMetadata(symbol: r'$', fallbackName: 'US Dollar'),
  'UYU': CurrencyMetadata(symbol: r'$U', fallbackName: 'Uruguayan Peso'),
  'UZS': CurrencyMetadata(symbol: r'soʻm', fallbackName: 'Uzbekistani Som'),
  'VES': CurrencyMetadata(symbol: r'Bs.S', fallbackName: 'Venezuelan Bolivar'),
  'VND': CurrencyMetadata(symbol: r'₫', fallbackName: 'Vietnamese Dong'),
  'VUV': CurrencyMetadata(symbol: r'VT', fallbackName: 'Vanuatu Vatu'),
  'WST': CurrencyMetadata(symbol: r'WS$', fallbackName: 'Samoan Tala'),
  'XAF': CurrencyMetadata(symbol: r'FCFA', fallbackName: 'Central African CFA Franc'),
  'XCD': CurrencyMetadata(symbol: r'EC$', fallbackName: 'East Caribbean Dollar'),
  'XOF': CurrencyMetadata(symbol: r'CFA', fallbackName: 'West African CFA Franc'),
  'XPF': CurrencyMetadata(symbol: r'₣', fallbackName: 'CFP Franc'),
  'YER': CurrencyMetadata(symbol: r'﷼', fallbackName: 'Yemeni Rial'),
  'ZAR': CurrencyMetadata(symbol: r'R', fallbackName: 'South African Rand'),
  'ZMW': CurrencyMetadata(symbol: r'ZK', fallbackName: 'Zambian Kwacha'),
  'ZWL': CurrencyMetadata(symbol: r'Z$', fallbackName: 'Zimbabwean Dollar'),
};
