spring.application.name=pnpios

currency.rates.api.url=https://api.nbp.pl
currency.rates.cache-file=cache/currency-rates.json
currency.rates.remote-enabled=true

spring.cloud.openfeign.client.config.currencyRatesClient.connectTimeout=3000
spring.cloud.openfeign.client.config.currencyRatesClient.readTimeout=5000
spring.cloud.openfeign.client.config.currencyRatesClient.loggerLevel=full

logging.level.pl.pg.pnpios.external.CurrencyRatesClient=DEBUG
logging.level.feign=DEBUG
